services:
  whatsapp-bot:
    build: 
      context: '.'
    image: whatsapp-voice:latest
    container_name: whatsapp-voice
    environment:
      - LOG_LEVEL=info
      - OLLAMA_NUM_GPU=0
      - OLLAMA_MODEL=llama3.2:1b
      - OLLAMA_BASE_URL=http://localhost:11434
    volumes:
      - ./session:/app/session
      - ./logs:/app/logs
      - ./temp:/app/temp
      - ./audio_cache:/app/audio_cache
    restart: unless-stopped
